backend:
  name: git-gateway
  branch: main
media_folder: "public/imgs"
public_folder: "/imgs"
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Cím", name: "title", widget: "string" }
      - { label: "Leírás", name: "description", widget: "string" }
      - { label: "Szerző", name: "author", widget: "string" }
      - { label: "Dátum", name: "date", widget: "datetime" }
      - { label: "Tagek", name: "tags", widget: "list", default: ["post"] }
      - { label: "Csatolt kép", name: "image", widget: "image" }
      - { label: "Kép leírás", name: "imageAlt", widget: "string" }
      - { label: "Szöveg", name: "body", widget: "markdown" }
